cli:
  - cli/**/*
website:
  - website/**/*

# source plugins
aws:
  - plugins/source/aws/**/*
azure:
  - plugins/source/azure/**/*
azuredevops:
  - plugins/source/azuredevops/**/*
cloudflare:
  - plugins/source/cloudflare/**/*
crowdstrike:
  - plugins/source/crowdstrike/**/*
digitalocean:
  - plugins/source/digitalocean/**/*
datadog:
  - plugins/source/datadog/**/*
fuzz:
  - plugins/source/fuzz/**/*
gandi:
  - plugins/source/gandi/**/*
gcp:
  - plugins/source/gcp/**/*
github:
  - plugins/source/github/**/*
heroku:
  - plugins/source/heroku/**/*
k8s:
  - plugins/source/k8s/**/*
okta:
  - plugins/source/okta/**/*
snyk:
  - plugins/source/snyk/**/*
tailscale:
  - plugins/source/tailscale/**/*
terraform:
  - plugins/source/terraform/**/*
vercel:
  - plugins/source/vercel/**/*

# destination plugins
bigquery:
  - plugins/destination/bigquery/**/*
csv:
  - plugins/destination/csv/**/*
postgresql:
  - plugins/destination/postgresql/**/*
snowflake:
  - plugins/destination/snowflake/**/*
sqlite:
  - plugins/destination/sqlite/**/*
